name: V8 Upgrade

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Run every day

jobs:
  upgrade:
    name: Upgrade V8
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Update depot_tools fetch config
        run: cd deps/depot_tools && git config --unset-all remote.origin.fetch; git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
        shell: bash
      - name: Add depot_tools to PATH
        run: echo "$PWD/deps/depot_tools" >> $GITHUB_PATH
        shell: bash
      - name: Run upgrade script
        run: cd deps && python upgrade_v8.py
      - name: Create PR metadata
        id: pr_metadata
        run: |
          echo ::set-output name=pr_branch::"v8_$(cat deps/v8_version)_upgrade"
          echo ::set-output name=pr_commit_message::"Upgrade V8 binaries for $(cat deps/v8_version) version"
          echo ::set-output name=pr_body::"Auto-generated pull request to upgrade V8 binary for $(cat deps/v8_version) version"
      - name: Create branch
        run: gh repo create-branch base_branch$(cat deps/v8_version) branch_to_merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changes
        run: git commit -am "Upgrade V8 binaries for $(cat deps/v8_version) version"
      - name: Push changes
        run: git push origin branch_to_merge
      - name: Create pull request
        run: gh pr create -B base_branch$(cat deps/v8_version) -H branch_to_merge --title 'Merge branch_to_merge into base_branch' --body 'Created by GitHub action, merge'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
